apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 2
  revisionHistoryLimit: 1 #limitaria el número de versiones guardadas
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
    #    - name: mi-aplicacion
    #      image: gcr.io/deep-theorem-461601-j3/mi-aplicacion:b6d213c #cambiar linea
        - name: mi-aplicacion
          image: gcr.io/devopsfarmacia/mi-aplicacion:87382f4
          ports:
            - containerPort: 8080
